language: python
python:
  - 3.4
install:
  - pip install -r requirements.txt
  - pip3 install coveralls
# script:
#   coverage run --source=moscowdjango,meetup manage.py test
# after_success:
#   coveralls