language: python
python:
  - 3.4
install:
  - pip install -r requirements.txt
  - pip install coverage
script: # section obligatoire pour python
  echo "TODO"
  coverage run vache.py test
after_success:
  coveralls