language: python
python:
  - 3.4
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
install:
  - pip install -r requirements.txt
script: # section obligatoire pour python
  - echo "TODO"
  - py.test --doctest-modules
after_success:
  - coveralls
